version: '3.8'

services:
  # API
  api:
    build: .  # Construye usando el Dockerfile de la carpeta actual
    container_name: smart_translator_api
    ports:
      - "8000"  # Expone el puerto 8000
    depends_on:
      - db
      - cache
    # Sobreescribimos localhost por los nombres de servicio
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/translator_db
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      # Pasamos la clave de DeepL desde tu archivo .env local
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - DEEPL_URL=${DEEPL_URL}
    env_file:
      - .env
  # Implementacián Nginx
  nginx:
    image: nginx:alpine
    container_name: smart_translator_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: smart_translator_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: translator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de Caché
  cache:
    image: redis:alpine
    container_name: smart_translator_redis
    restart: always

volumes:
  postgres_data: