version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: smart_translator_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: translator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servicio de Cach√©
  cache:
    image: redis:alpine
    container_name: smart_translator_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: